[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["0805004949"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
requests = "^2.28.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"